# Generated by Django 5.2.5 on 2026-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
